[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  PHP_VERSION = "8.1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
